import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
} from "docx";
import PptxGenJS from "pptxgenjs";
import PDFDocument from "pdfkit";
import * as XLSX from "xlsx";

export interface DocSection {
  heading?: string;
  level?: 1 | 2 | 3;
  paragraphs: string[];
}

export interface DocxContent {
  title: string;
  sections: DocSection[];
}

export interface XlsxSheet {
  name: string;
  headers: string[];
  rows: string[][];
}

export interface XlsxContent {
  sheets: XlsxSheet[];
}

export interface PptxSlide {
  title: string;
  bullets?: string[];
  content?: string;
  notes?: string;
}

export interface PptxContent {
  title: string;
  slides: PptxSlide[];
}

export async function generateDocxBuffer(content: DocxContent): Promise<Buffer> {
  const children: Paragraph[] = [];

  children.push(
    new Paragraph({
      text: content.title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    })
  );

  for (const section of content.sections) {
    if (section.heading) {
      const headingMap: Record<number, (typeof HeadingLevel)[keyof typeof HeadingLevel]> = {
        1: HeadingLevel.HEADING_1,
        2: HeadingLevel.HEADING_2,
        3: HeadingLevel.HEADING_3,
      };
      children.push(
        new Paragraph({
          text: section.heading,
          heading: headingMap[section.level ?? 1],
          spacing: { before: 320, after: 160 },
        })
      );
    }

    for (const para of section.paragraphs) {
      if (!para.trim()) continue;
      children.push(
        new Paragraph({
          children: [new TextRun({ text: para, size: 24 })],
          spacing: { after: 120, line: 360 },
        })
      );
    }
  }

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by Nexa AI · ${new Date().toLocaleDateString()}`,
          size: 18,
          color: "999999",
          italics: true,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { before: 600 },
    })
  );

  const doc = new Document({ sections: [{ children }] });
  return Packer.toBuffer(doc);
}

export function generateXlsxBuffer(content: XlsxContent): Buffer {
  const wb = XLSX.utils.book_new();

  for (const sheet of content.sheets) {
    const aoa = [sheet.headers, ...sheet.rows];
    const ws = XLSX.utils.aoa_to_sheet(aoa);

    // Bold header row
    const range = XLSX.utils.decode_range(ws["!ref"] ?? "A1");
    for (let col = range.s.c; col <= range.e.c; col++) {
      const cellAddr = XLSX.utils.encode_cell({ r: 0, c: col });
      if (!ws[cellAddr]) continue;
      ws[cellAddr].s = { font: { bold: true } };
    }

    XLSX.utils.book_append_sheet(wb, ws, sheet.name.slice(0, 31));
  }

  return XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;
}

export async function generatePptxBuffer(content: PptxContent): Promise<Buffer> {
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: "FFFFFF" };
  titleSlide.addText(content.title, {
    x: 0.5,
    y: 2.0,
    w: "90%",
    h: 1.5,
    fontSize: 36,
    bold: true,
    align: "center",
    color: "1a1a1a",
  });
  titleSlide.addText(`Generated by Nexa AI · ${new Date().toLocaleDateString()}`, {
    x: 0.5,
    y: 4.0,
    w: "90%",
    h: 0.5,
    fontSize: 14,
    align: "center",
    color: "999999",
  });

  for (const slide of content.slides) {
    const s = pptx.addSlide();
    s.background = { color: "FFFFFF" };

    s.addText(slide.title, {
      x: 0.5,
      y: 0.3,
      w: "90%",
      h: 0.8,
      fontSize: 24,
      bold: true,
      color: "1a1a1a",
    });

    if (slide.bullets && slide.bullets.length > 0) {
      const bulletItems = slide.bullets.map((b) => ({
        text: b,
        options: { bullet: true, fontSize: 16, color: "333333", paraSpaceAfter: 8 },
      }));
      s.addText(bulletItems, {
        x: 0.5,
        y: 1.3,
        w: "90%",
        h: 4.5,
        valign: "top",
      });
    } else if (slide.content) {
      s.addText(slide.content, {
        x: 0.5,
        y: 1.3,
        w: "90%",
        h: 4.5,
        fontSize: 16,
        color: "333333",
        valign: "top",
        wrap: true,
      });
    }

    if (slide.notes) {
      s.addNotes(slide.notes);
    }
  }

  return (await pptx.write({ outputType: "nodebuffer" })) as Buffer;
}

export function generatePdfBuffer(content: DocxContent): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 60, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Title
    doc.font("Helvetica-Bold").fontSize(22).text(content.title, { align: "center" });
    doc.moveDown(1.5);
    doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor("#cccccc").stroke();
    doc.moveDown(1);

    const headingFontSizes: Record<number, number> = { 1: 16, 2: 14, 3: 12 };

    for (const section of content.sections) {
      if (section.heading) {
        const fs = headingFontSizes[section.level ?? 1];
        doc.font("Helvetica-Bold").fontSize(fs).fillColor("#1a1a1a").text(section.heading);
        doc.moveDown(0.4);
      }

      for (const para of section.paragraphs) {
        if (!para.trim()) continue;
        doc.font("Helvetica").fontSize(11).fillColor("#333333").text(para, { lineGap: 4 });
        doc.moveDown(0.5);
      }

      doc.moveDown(0.3);
    }

    const bottomY = doc.page.height - 60;
    doc.font("Helvetica-Oblique")
      .fontSize(9)
      .fillColor("#999999")
      .text(
        `Generated by Nexa AI · ${new Date().toLocaleDateString()}`,
        60,
        bottomY,
        { align: "center" }
      );

    doc.end();
  });
}
